# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oven', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='txt',
            field=models.CharField(max_length=100000),
        ),
    ]
