# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oven', '0002_auto_20170322_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='bio',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
